name: yuhuaren_app
description: Application connecting YuHua Alumni
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  #routing
  go_router: ^6.5.6
  #multi lingual
  flutter_localization: ^0.1.10
  intl: ^0.18.1
  #ui lib
  flutter_otp_text_field: ^1.1.1
  table_calendar: ^3.0.9
  #dependency injection
  get_it: ^7.3.0
  injectable: ^2.1.1
  #state management
  flutter_bloc: ^8.1.2
  #util
  flutter_native_splash: ^2.2.19
  flutter_launcher_icons: ^0.13.0
  time: ^2.1.3
  json_annotation: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.5
  build_runner: ^2.3.3
  json_serializable: ^6.6.1


flutter:

  uses-material-design: true

  assets:
    - assets/images/

flutter_native_splash:
  background_image: assets/images/background.png
  image: assets/images/splash.png
  android_12:
    color: #403F88
    image: assets/images/splash_android.png
  web: false

flutter_icons:
  image_path_ios: assets/images/logo.png
  image_path_android: assets/images/logo_android.png
  android: true
  ios: true
  remove_alpha_ios: true
  adaptive_icon_background: #403F88
  adaptive_icon_foreground: #403F88
  min_sdk_android: 21